# Binder source rules for service programs
# The binder source defines which procedures are exported from the service program

PROJECT_BNDDIR := INABIND1
PROJECT_OPTION := *DUPPROC *DUPVAR

SUBNUM.SRVPGM: private BNDDIR := $(PROJECT_BNDDIR)
SUBNUM.SRVPGM: private OPTION := $(PROJECT_OPTION)

DIVNUM.SRVPGM: private BNDDIR := $(PROJECT_BNDDIR)
DIVNUM.SRVPGM: private OPTION := $(PROJECT_OPTION)

MULTNUM.SRVPGM: private BNDDIR := $(PROJECT_BNDDIR)
MULTNUM.SRVPGM: private OPTION := $(PROJECT_OPTION)

OP_SRCH.SRVPGM: private BNDDIR := $(PROJECT_BNDDIR)
OP_SRCH.SRVPGM: private OPTION := $(PROJECT_OPTION)

SUBNUM.SRVPGM: SUBNUM.BND SUBNUM.MODULE
DIVNUM.SRVPGM: DIVNUM.BND DIVNUM.MODULE
MULTNUM.SRVPGM: MULTNUM.BND MULTNUM.MODULE
OP_SRCH.SRVPGM: OP_SRCH.BND OP_SRCH.MODULE

# IBMi Tobi doesn't seem to expand patterns/wildcards on dependencies/prerequisites
# %.SRVPGM: private BNDDIR := $(PROJECT_BNDDIR)
# %.SRVPGM: private OPTION := $(PROJECT_OPTION)
# %.SRVPGM: %.BND %.MODULE
